runtime: nodejs16

entrypoint: node out/index.js

handlers:
  - url: /assets/(.*\.json)
    static_files: assets/\1
    upload: assets/(.*\.json)

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /static
    static_dir: public
